version: 2.1

orbs:
  node: circleci/node@4.1
  codecov: codecov/codecov@1.2.5

jobs:
  tests:
    docker:
      - image: circleci/node:14.17.3-browsers

    steps:
      - checkout
      - node/install-yarn
      - run:
          name: Show node version
          command: |
            node --version
            yarn --version
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run lint check
          command: yarn lint
      - run:
          name: Run unit tests with coverage
          command: yarn cover
      - codecov/upload:
          file: coverage/*.json
      - run:
          name: Publish to Chromatic
          command: yarn chromatic  --project-token=${CHROMATIC_TOKEN}

  versioning:
    docker:
      - image: circleci/node:14.17.3

    steps:
      - checkout
      - run:
          name: Check package version
          command: node scripts/check-version wagnervieira1209 autoescola-nardini

workflows:
  ci:
    jobs:
      - tests
      - versioning:
          filters:
            branches:
              ignore: main
            tags:
              ignore: /.*/
